// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20260303151050_CreateBookEntity")]
    partial class CreateBookEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Author");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("LastUpdatedDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Book", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Author = "Eric Evans Author",
                            CreatedDate = new DateTime(2026, 3, 3, 0, 0, 0, 0),
                            Description = "Classic reference for strategic and tactical domain-driven design.",
                            Title = "Domain-Driven Design Book"
                        },
                        new
                        {
                            Id = 2L,
                            Author = "Robert Martin Author",
                            CreatedDate = new DateTime(2026, 3, 3, 0, 0, 0, 0),
                            Description = "Practical guidance on layered architecture and maintainable software systems.",
                            Title = "Clean Architecture Guide"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
